spring:
  application:
    name: kws
# DBMS
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kws
    username: root
    password: 1114
# JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          show_sql: true
          format_sql: true