spring:
  application:
    name: kws

# DBMS
  datasource:
    url: jdbc:mariadb://localhost:3306
    username: user1
    password: 1114
    driver-class-name: org.mariadb.jdbc.Driver
# JPA
    jpa:
        hibernate:
        ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
